<a href="https://colab.research.google.com/github/Sakshi-coder1/workco/blob/main/DSP_2_(1)_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.array([2,5,6,36,78])
print(a)

[ 2  5  6 36 78]


In [3]:
b=np.array([[4,6], [7,2]])
print(b)


[[4 6]
 [7 2]]


In [4]:
c=a+5
print(c)

[ 7 10 11 41 83]


In [5]:
d=a*3
print(d)


[  6  15  18 108 234]


In [6]:
print("Mean",np.mean(a))

Mean 25.4


In [7]:
print("sum",np.sum(a))


sum 127


In [8]:
print("Maxium number",np.max(a))

Maxium number 78


In [9]:
arr=np.array([10,20,30,40])
print(arr[3])

40


In [10]:
print(arr[0:3])


[10 20 30]
